### ISSUE TITLE
AMDGPU-Pro updated 16.40.4

### ISSUE THREAD

**Issue by wbsdty331** [corngood/archlinux-amdgpu#17]
AMD updated amdgpu-pro 16.40.4, you can find it on steamos repository.
http://repo.steampowered.com/steamos/pool/non-free/a/amdgpu-pro-dkms/

The version is 16.40.4,but AMD Website is only 16.30.3 : http://support.amd.com/en-us/kb-articles/Pages/AMD-Radeon-GPU-PRO-Linux-Beta-Driver%E2%80%93Release-Notes.aspx

I don't understand why AMD only provide latest version for steamos, I haven't yet tried this version, So I can't promise it will works good on ArchLinux.

Thanks!

**Comment by corngood** [comment]
Yeah that's really frustrating.  It looks like it's packed in a different manner.  I'll take a look in the deb, but if it's not similar to the official releases, I think I'll wait until either they release it properly, or someone really wants something from this version.

There's a thread about it here: https://www.phoronix.com/forums/forum/linux-graphics-x-org-drivers/amd-linux/881337-new-amdgpu-pro-release-appeared-in-the-steamos-repo-16-40-0

**Comment by wbsdty331** [comment]
Oh my god, Look at here:
http://repo.steampowered.com/steamos/pool/non-free/a/amdgpu-pro-dkms/

amdgpu-pro updated to `16.40.4-317586`, without any news and release note.

**Comment by Kozzi11** [comment]
https://www2.ati.com/drivers/linux/ubuntu/amdgpu-pro-16.40-348864.tar.xz

**Comment by wbsdty331** [comment]
@corngood

**Comment by corngood** [comment]
Sorry I haven't had a chance to update this yet.  I've actually being working mostly on NixOS for the last little while.

If anyone wants to have a go at updating, https://github.com/NixOS/nixpkgs/pull/19936/commits/4dbedb4ce78ba8191c4a9954d57339e3e54da6fe has the nix changes, including the patches needed for linux-4.8.

**Comment by Jhackler** [comment]
The 16.40 is on amd for non steam as mentioned by kozi11

**Comment by wolf9466** [comment]
Please supply something for this - I'd really, REALLY love to use it for OpenCL work, as they usually put out one or more really, really bad drivers (only talking about the OpenCL compiler here), and then suddenly it's better again. Since AMDGPU has definitely caused performance loss for me, I'm hoping this is the golden driver of the next few releases.

**Comment by corngood** [comment]
Closing in favour of #24
