### ISSUE TITLE
Corngood. Them patches tho.

### ISSUE THREAD

**Issue by maxcr** [corngood/archlinux-amdgpu#21]
Hey man I know you have 1000 lines of code to edit and you have the patches to make this work. If you don't mind creating a branch with those unapplied patches so I can go through with adding them I'd appreciate it.

I really can't wait and have all the time in the world to get those patches applied and this bitch working by the end of the week.

If you think porting the steamOS AMDGPU-Pro driver should be enough then I'll start there. I just need some resources of which gentoo patches, and steamOS patches should be applied and I'll handle the rest. Thanks man.

**Comment by corngood** [comment]
We should probably discuss this on #16.  If anyone wants to add or edit patches, gen-PKGBUILD will include *.patch from the root of the repository, so you can just make a PR with some patch files added.

Now that 4.8 is out I'm happy to take a PR from anyone who can get it working (ideally without breaking 4.7).
