### ISSUE TITLE
AMDGPU-PRO 16.50 is out

### ISSUE THREAD

**Issue by solazs** [corngood/archlinux-amdgpu#24]
http://support.amd.com/en-us/kb-articles/Pages/AMDGPU-PRO-Driver-for-Linux-Release-Notes.aspx

It finally supports GCN 1.0 cards and freesync, could you take a look into it?

**Comment by Astilex5** [comment]
@corngood  I hate bumping issues. Especially on github. But is this being worked on? I am at the point of my Arch Install where I need to install drivers and the current AMDGPU-PRO is very out of date and I would hate to have to resort to open-source drivers. thx in advance.

**Comment by corngood** [comment]
I haven't had time to work on it recently.  Now that the open source vulkan driver is making progress, it's hard for me to justify spending time repackaging proprietary drivers.  I'm happy to accept pull requests from anyone who gets it working, and I can hand over maintainership of the AUR package if anyone wants it.

Cheers

**Comment by Valmar33** [comment]
@Astilex5 

Why not just use radeonsi or amdgpu?

What's your GPU?

**Comment by Astilex5** [comment]
On my Laptop its a HD7330 its all integrated as for my tower I have installed a EVGA GT 730 I have given up on AMD hardware entirely (my tower had a messed up vbios so that was the straw breaker for me) And as for performance have you tried playing Metro 2033 redux on radeonsi + mesa it absolutely unplayable. OS drivers are not usually recommended for gaming on old hardware. Which is why AGP would be great to have available.

**Comment by solazs** [comment]
@Valmar33 

My notebook is a hybrid graphics setup: integrated Intel 530 + radeon R7 M370

Sea Islands cards have no proper support with amdgpu (as of last week). I've tried it (compiled a linux 4.9 kernel with the experimental support), but it froze solid every time I tried to use the discrete card.

See http://www.phoronix.com/scan.php?page=article&item=amdgpu-1650-relive&num=1

>GCN 1.0 / Southern Islands Support: With Linux 4.9 the AMDGPU DRM driver added experimental GCN 1.0 / Southern Islands support, which is disabled by default at the kernel's build time. With the AMDGPU-PRO 16.50 release, its DKMS kernel module ships with the GCN 1.0 support enabled along with a supported user-space stack. Indeed, now with the Radeon HD 7000 series GPUs and other GCN 1.0 GPUs tested, there is OpenGL 4.5 and OpenCL atop the hybrid driver stack. Unfortunately, it wasn't stable at all. I was unable to get any GCN 1.0 benchmarks to share today as it was consistently hanging while running graphics tests, sometimes even when just launching Steam. But when popping in newer GCN hardware, those problems didn't appear atop this AMDGPU-PRO stack. So while the GCN 1.0 support is there for AMDGPU-PRO, your mileage may vary upon how usable it is. It's also possible AMD has corrected some GCN 1.0 regressions since they spun their Linux "press" driver for me.


Didn't have much success with the radeon driver either.
I'm stuck on the integrated intel card.

**Comment by Astilex5** [comment]
@solazs Are you running Arch? Or did you do this on Ubuntu/REHL Distro if you used the Arch Linux AUR package it is still dated back to 16.30 and is reported not to work with 1.0 GCN Cards. As for fglrx not working I have never had any issues other than havong to go the extra mile to install it. That is just my experience however.

**Comment by solazs** [comment]
@Astilex5 

Yup, I'm running Arch. I haven't tried amdgpu-pro, just the opensource kernel driver, amdgpu.
My comment was intended to justify my need for amdgpu-pro.

Fglrx could work, I guess, but it's not exactly stable (or so I've heard), so I've never invested too much time in installing it.

Without any time for gaming, I'm fine with intel, but I prefer things to work than to just consume space in a notebook :smile:

**Comment by Astilex5** [comment]
@solazs That is fine I was just wondering. Fglrx is not as bad as people make it out to be while yes you can't use gnome/cinnamon with it, It does work with every other DE just fine I find the people who complain the most about it are those who tinker and mess with more damaging parts of the system and then fglrx will have a fit about it. (which is fixable btw). Arch Linux has an extensive [Wiki](https://wiki.archlinux.org/index.php/AMD_Catalyst) on how to use it. I would use the Unofficial mirror that is available as they are updated more frequently. If you use it casually then you should be fine.

But in the end yes we do have a need for updated drivers but for now we should take what we have and make the best of it.

Cheers Mate!

**Comment by corngood** [comment]
If anyone is interested, some progress was made on #23.  That PR has a PKGBUILD for 16.40, and the update to 16.50 should be pretty simple.

I've updated the patches on NixOS for linux-4.8 (https://github.com/corngood/nixpkgs/tree/amdgpu-pro-update/pkgs/os-specific/linux/amdgpu-pro/patches), so those would need to be pulled in and tested.

I'm happy to help, but I don't currently have an Arch system with AMD hardware, which is why I haven't done the update myself.

**Comment by Astilex5** [comment]
@corngood sadly I do not have the hardware to run 16.40 with the 4.8 kernel the hardware that I had that worked with 16.40 when I made my first post was an intergrated r7 with a ****** up vbios so I can't help there anymore.

I also have to return to school in a week so I won't really be much help if something goes wrong when I am there. I can test 16.50 when someone gets its up so I will keep and eye on this.

If you do need help you can just tag me and I will see what I can do. I check my email constantly.

**Comment by starks** [comment]
I've been playing around with this, but I haven't been able to get it work on my hardware (HD4000+7730M).

https://github.com/sbilo/archlinux-amdgpu/tree/update-for-16.50

**Comment by corngood** [comment]
What's the problem?  Is it failing to build?

**Comment by starks** [comment]
It builds, I just can't figure out what kind of PowerXpress support the driver has. There's no GUI and no tools.

**Comment by corngood** [comment]
Are you trying to run entirely on the amd gpu, rather than using something like (https://wiki.archlinux.org/index.php/PRIME)?

Does it worth with the open source drivers or fglrx?

Unfortunately I don't have any experience getting this to work on a dual gpu system.

**Comment by starks** [comment]
I've worked with both Optimus and PowerXpress unfortunately. 

You can't run entirely on the AMD GPU, the Intel GPU is responsible for display and monitor connections. At least that's how PRIME works, where the AMD GPU's OpenGL, OpenCL, hw acceleration, etc are called as needed and the radeon driver powersaving kicks in for everything else.

fglrx works on these laptops. The AMD card is always on and every application runs on it. I imagine that AMDGPU-PRO is the same, but there's no guidance on how to set libraries and X to use the proper paths and drivers.

**Comment by corngood** [comment]
It would be great if someone could test your PKGBUILD on a discrete desktop GPU.  You don't happen to have access to one?

If not, any volunteers?

**Comment by starks** [comment]
I'm using sbilo's PKGBUILD and I haven't made any changes. Save for a few nags about 32-bit support, it looks complete.

There are really no good options for mobile GCN 1.0 at the moment. You either stay with radeon/radeonsi or run the open-source amdgpu with a custom kernel.

**Comment by dylanaraps** [comment]
I'm happy to test it out, I've got a single `7950` using the kernel `amdgpu` right now. If I need any help I'll let you guys know.

**Comment by dylanaraps** [comment]
I got @starks's PKGBUILD to build but I can't get it to install. Are there any prerequisites or dependencies I should know about? Pacman complains about unresolvable dependencies, any ideas?

**Comment by corngood** [comment]
Could you post the output?

**Comment by dylanaraps** [comment]
```sh
dylan ~/aur/archlinux-amdgpu >makepkg -i
==> WARNING: The package group has already been built, installing existing packages...
==> Installing amdgpu-pro-installer package group with pacman -U...
loading packages...
resolving dependencies...
warning: cannot resolve "lib32-amdgpu-pro-dkms=16.50.362463-1", a dependency of "lib32-amdgpu-pro"
warning: cannot resolve "lib32-cunit", a dependency of "lib32-libdrm-amdgpu-pro-utils"
warning: cannot resolve "lib32-libdrm-amdgpu-pro-utils=16.50.362463-1", a dependency of "lib32-amdgpu-pro"
warning: cannot resolve "lib32-libgbm1-amdgpu-pro-base=16.50.362463-1", a dependency of "lib32-libgbm1-amdgpu-pro"
warning: cannot resolve "lib32-libgbm1-amdgpu-pro=16.50.362463-1", a dependency of "lib32-amdgpu-pro"
warning: cannot resolve "lib32-libgl1-amdgpu-pro-appprofiles=16.50.362463-1", a dependency of "lib32-amdgpu-pro"
warning: cannot resolve "lib32-libtinfo>=6", a dependency of "lib32-libvdpau-amdgpu-pro"
warning: cannot resolve "lib32-libvdpau-amdgpu-pro=16.50.362463-1", a dependency of "lib32-amdgpu-pro"
warning: cannot resolve "lib32-libgbm1-amdgpu-pro-base=16.50.362463-1", a dependency of "lib32-libgbm1-amdgpu-pro"
warning: cannot resolve "lib32-libgbm1-amdgpu-pro=16.50.362463-1", a dependency of "lib32-xserver-xorg-video-glamoregl-amdgpu-pro"
warning: cannot resolve "lib32-xserver-xorg-video-glamoregl-amdgpu-pro=16.50.362463-1", a dependency of "lib32-amdgpu-pro"
warning: cannot resolve "lib32-libgbm1-amdgpu-pro-base=16.50.362463-1", a dependency of "lib32-libgbm1-amdgpu-pro"
warning: cannot resolve "lib32-libgbm1-amdgpu-pro=16.50.362463-1", a dependency of "lib32-xserver-xorg-video-amdgpu-pro"
warning: cannot resolve "lib32-libsystemd>=183", a dependency of "lib32-xserver-xorg-video-amdgpu-pro"
warning: cannot resolve "lib32-xserver-xorg-video-amdgpu-pro=16.50.362463-1", a dependency of "lib32-amdgpu-pro"
warning: cannot resolve "cunit", a dependency of "libdrm-amdgpu-pro-utils"
warning: cannot resolve "libdrm-amdgpu-pro-utils=16.50.362463-1", a dependency of "amdgpu-pro"
warning: cannot resolve "libtinfo>=6", a dependency of "libvdpau-amdgpu-pro"
warning: cannot resolve "libvdpau-amdgpu-pro=16.50.362463-1", a dependency of "amdgpu-pro"
warning: cannot resolve "libdrm-amdgpu-pro-amdgpu1:i386", a dependency of "amdgpu-pro-lib32"
warning: cannot resolve "libgbm1-amdgpu-pro:i386", a dependency of "amdgpu-pro-lib32"
warning: cannot resolve "libgl1-amdgpu-pro-glx:i386", a dependency of "amdgpu-pro-lib32"
warning: cannot resolve "libgl1-amdgpu-pro-dri:i386", a dependency of "amdgpu-pro-lib32"
warning: cannot resolve "libgles2-amdgpu-pro:i386", a dependency of "amdgpu-pro-lib32"
warning: cannot resolve "vulkan-amdgpu-pro:i386", a dependency of "amdgpu-pro-lib32"
warning: cannot resolve "libvdpau-amdgpu-pro:i386", a dependency of "amdgpu-pro-lib32"
warning: cannot resolve "libopencl1-amdgpu-pro:i386", a dependency of "amdgpu-pro-lib32"
warning: cannot resolve "opencl-amdgpu-pro-icd:i386", a dependency of "amdgpu-pro-lib32"
warning: cannot resolve "lib32-libglib2.0-0>=2.37.3", a dependency of "lib32-gst-omx-amdgpu-pro"
warning: cannot resolve "lib32-libgstreamer-plugins-base1.0-0>=1.6.0", a dependency of "lib32-gst-omx-amdgpu-pro"
warning: cannot resolve "lib32-libgstreamer1.0-0>=1.0.0", a dependency of "lib32-gst-omx-amdgpu-pro"
warning: cannot resolve "lib32-libomxil-bellagio0", a dependency of "lib32-gst-omx-amdgpu-pro"
warning: cannot resolve "libglib2.0-0>=2.37.3", a dependency of "gst-omx-amdgpu-pro"
warning: cannot resolve "libgstreamer-plugins-base1.0-0>=1.6.0", a dependency of "gst-omx-amdgpu-pro"
warning: cannot resolve "libgstreamer1.0-0>=1.0.0", a dependency of "gst-omx-amdgpu-pro"
warning: cannot resolve "libomxil-bellagio0", a dependency of "gst-omx-amdgpu-pro"
warning: cannot resolve "cunit", a dependency of "libdrm-amdgpu-pro-utils"
warning: cannot resolve "lib32-cunit", a dependency of "lib32-libdrm-amdgpu-pro-utils"
warning: cannot resolve "lib32-libgbm1-amdgpu-pro-base=16.50.362463-1", a dependency of "lib32-libgbm1-amdgpu-pro"
warning: cannot resolve "lib32-libgbm1-amdgpu-pro-base=16.50.362463-1", a dependency of "lib32-libgbm1-amdgpu-pro"
warning: cannot resolve "lib32-libgbm1-amdgpu-pro=16.50.362463-1", a dependency of "lib32-libgbm1-amdgpu-pro-dev"
warning: cannot resolve "lib32-libgbm1-amdgpu-pro-base=16.50.362463-1", a dependency of "lib32-libgbm1-amdgpu-pro"
warning: cannot resolve "lib32-libgbm1-amdgpu-pro=16.50.362463-1", a dependency of "lib32-xserver-xorg-video-glamoregl-amdgpu-pro"
warning: cannot resolve "lib32-xserver-xorg-video-glamoregl-amdgpu-pro=16.50.362463-1", a dependency of "lib32-libglamor-amdgpu-pro-dev"
warning: cannot resolve "lib32-libtinfo>=6", a dependency of "lib32-libvdpau-amdgpu-pro"
warning: cannot resolve "libtinfo>=6", a dependency of "libvdpau-amdgpu-pro"
warning: cannot resolve "lib32-libomxil-bellagio0", a dependency of "lib32-mesa-amdgpu-pro-omx-drivers"
warning: cannot resolve "lib32-libtinfo>=6", a dependency of "lib32-mesa-amdgpu-pro-omx-drivers"
warning: cannot resolve "libomxil-bellagio0", a dependency of "mesa-amdgpu-pro-omx-drivers"
warning: cannot resolve "libtinfo>=6", a dependency of "mesa-amdgpu-pro-omx-drivers"
warning: cannot resolve "lib32-libgbm1-amdgpu-pro-base=16.50.362463-1", a dependency of "lib32-libgbm1-amdgpu-pro"
warning: cannot resolve "lib32-libgbm1-amdgpu-pro=16.50.362463-1", a dependency of "lib32-xserver-xorg-video-amdgpu-pro"
warning: cannot resolve "lib32-libsystemd>=183", a dependency of "lib32-xserver-xorg-video-amdgpu-pro"
warning: cannot resolve "lib32-libgbm1-amdgpu-pro-base=16.50.362463-1", a dependency of "lib32-libgbm1-amdgpu-pro"
warning: cannot resolve "lib32-libgbm1-amdgpu-pro=16.50.362463-1", a dependency of "lib32-xserver-xorg-video-glamoregl-amdgpu-pro"
warning: cannot resolve "lib32-libsystemd>=183", a dependency of "lib32-xserver-xorg-video-modesetting-amdgpu-pro"
:: The following packages cannot be upgraded due to unresolvable dependencies:
      lib32-amdgpu-pro  amdgpu-pro  amdgpu-pro-lib32  lib32-gst-omx-amdgpu-pro  gst-omx-amdgpu-pro  libdrm-amdgpu-pro-utils  lib32-libdrm-amdgpu-pro-utils
      lib32-libgbm1-amdgpu-pro  lib32-libgbm1-amdgpu-pro-dev  lib32-libglamor-amdgpu-pro-dev  lib32-libvdpau-amdgpu-pro  libvdpau-amdgpu-pro
      lib32-mesa-amdgpu-pro-omx-drivers  mesa-amdgpu-pro-omx-drivers  lib32-xserver-xorg-video-amdgpu-pro  lib32-xserver-xorg-video-glamoregl-amdgpu-pro
      lib32-xserver-xorg-video-modesetting-amdgpu-pro

:: Do you want to skip the above packages for this upgrade? [y/N] 

```

**Comment by stonewalljones** [comment]
I've got an RX-480 and I would be willing to help test the new patch.

**Comment by asdkant** [comment]
I've got an RX 460 and would be willing to help test the new patch

**Comment by apemanzilla** [comment]
R9-390 here, if you ever need to test with GCN 2.

**Comment by corngood** [comment]
Closing this in favour of #27
