### ISSUE TITLE
Detach your fork

### ISSUE THREAD

**Issue by Xaekai** [corngood/archlinux-amdgpu#29]
You should contact GitHub support and make this fork the parent of the network, as mentioned [here](https://help.github.com/articles/why-are-my-contributions-not-showing-up-on-my-profile/#commit-was-made-in-a-fork)

**Comment by MartB** [comment]
:+1:

**Comment by corngood** [comment]
Good idea.  I didn't know this could be done through support.  Request made.

**Comment by corngood** [comment]
Done
