### ISSUE TITLE
amdgpu working fine with 4.10 without dkms package

### ISSUE THREAD

**Issue by fjfalcon** [corngood/archlinux-amdgpu#45]
Greetings. Just tested - amdgpu-pro works fine on 4.10 kernel without dkms package.
How should i test it - that all working fine?

**Comment by corngood** [comment]
Running the smoketest from the vulkan SDK would be a good start.  Also check your xorg log for warnings about the 'hybrid' driver.

It's possible that you'll just be missing features or have poor performance in certain workloads.

**Comment by fjfalcon** [comment]
Youp, hybrid driver not loaded. Sad.
