### ISSUE TITLE
no libdrm?

### ISSUE THREAD

**Issue by mikel392** [corngood/archlinux-amdgpu#46]
doesnt it provide libdrm? alot of programs that require libdrm don't want to install
`-- Checking for modules 'gtk+-3.0;appindicator3-0.1'
--   Package 'libdrm', required by 'egl', not found
--   Package 'libdrm', required by 'egl', not found
CMake Error at /usr/share/cmake-3.7/Modules/FindPkgConfig.cmake:415 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.7/Modules/FindPkgConfig.cmake:588 (_pkg_check_modules_internal)
  CMakeLists.txt:25 (pkg_check_modules)
`

**Comment by corngood** [comment]
It has libdrm.so, but no .pc and I don't think it had headers, so it's not suitable as a build dependency.  I'm actually not sure of the best way to deal with this.  Suggestions are welcome.

**Comment by mikel392** [comment]
i have no idea how the build dependency system works yet, so i wouldn't know how to deal with this.

**Comment by mikel392** [comment]
closing this issue, but only because i have found a workaround. i temporarily uninstall amdgpu-pro-libdrm and lib32-amdgpu-pro-libdrm and install libdrm and lib32-libdrm and install whatever wanted librm then uninstall and install amds libdrm package back.
