### ISSUE TITLE
AMDGPU-PRO 17.10 is out

### ISSUE THREAD

**Issue by fjfalcon** [corngood/archlinux-amdgpu#47]
http://support.amd.com/en-us/kb-articles/Pages/AMDGPU-PRO-Driver-for-Linux-Release-Notes.aspx

**Comment by fjfalcon** [comment]
As far as i see from deb content there is still no support for 1.19 xorg server...

**Comment by corngood** [comment]
I made #48 with my changes from NixOS.  I'm not able to test it though, so any testing would be appreciated.  The dkms module _should_ compile on linux 4.8 or 4.9, and it will still need xorg 1.18.

**Comment by corngood** [comment]
Thanks for testing it.  Fixed in #48
