### ISSUE TITLE
amdgpu-pro-firmware package misplaces lib-folder

### ISSUE THREAD

**Issue by JPT580** [corngood/archlinux-amdgpu#6]
I'm not 100% certain if i did everything correct, but since /lib is a symlink on my current Arch Linux installation, pacman complained about /lib already existing when trying to install the package amdgpu-pro-firmware.

Perhaps it is a solution to move that lib-folder into the usr-folder which the package provides?

Below is the snippet that i added the move instruction to:
```
package_amdgpu-pro-firmware () {
        pkgdesc="Firmware for amdgpu-pro cards."
        depends=()
        arch=('x86_64')

        rm -Rf "${srcdir}"/amdgpu-pro-firmware_16.30.3-306809_amd64
        mkdir "${srcdir}"/amdgpu-pro-firmware_16.30.3-306809_amd64
        cd "${srcdir}"/amdgpu-pro-firmware_16.30.3-306809_amd64
        ar x "${srcdir}"/amdgpu-pro-driver/./amdgpu-pro-firmware_16.30.3-306809_amd64.deb
        tar -C "${pkgdir}" -xf data.tar.xz
        mv "${pkgdir}/lib" "${pkgdir}/usr/" # <-- this is new
}
```

**Comment by corngood** [comment]
Thanks for the fix.  The -core package was already doing this, so it seems like the best approach.
