### ISSUE TITLE
Building anything from the AUR which requires OpenGL includes/headers with CMake at least fails because it can't find them

### ISSUE THREAD

**Issue by headkase** [corngood/archlinux-amdgpu#7]
When building a package from the AUR which requires OpenGL includes/headers at least with CMake the build process will fail because it cannot find them.  This is confirmed with rbdoom and gzdoom.

**Comment by corngood** [comment]
On my system, gl.h comes from the 'mesa' package.  It appears that other packages providing 'libgl', for example 'nvidia-libgl' also don't provide headers.

I could make mesa a dependency of the libgl packages, or rbdoom could add a makedep on mesa.  From looking at various PKGBUILDs it seems that there quite a few things with makedeps on mesa for this reason.

Thoughts?

**Comment by headkase** [comment]
I uninstalled all the Pro packages with -Rdd (as other packages wanted something that provided libgl) and then reinstalled mesa-libgl and lib32-mesa-libgl.  The packages build correctly after that.  I already had the mesa package installed when the building errors occurred, so it would seem that the issue is not in the mesa package but rather in something that the mesa-libgl package provides.

**Comment by corngood** [comment]
Are you sure you're missing headers?  Someone else reported a linker error on the AUR page:

`/usr/bin/ld: cannot find -lGL`

That would be because the libs are not in a standard location.

**Comment by headkase** [comment]
I don't know if it's the headers.  CMake says (paraphrased) that it can't find "OpenGL" or such.  Sorry, I've since uninstalled Pro and am going by hazy memory.  A small test for yourself is to try to compile "gzdoom" from the AUR.  It isn't that big and it spits out the error.

**Comment by conihorse** [comment]
I reported the "/usr/bin/ld: cannot find -lGL" on the AUR page. 

As per headkase's suggestion, I tryed to compile gzdoom from the AUR and it also fails, with the output below:

-- Looking for itoa
-- Looking for itoa - not found
-- Performing Test DUMB_CAN_USE_SSE
-- Performing Test DUMB_CAN_USE_SSE - Success
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Could NOT find OpenGL (missing:  OPENGL_gl_LIBRARY) 
-- Checking for module 'gtk+-2.0'
--   Found gtk+-2.0, version 2.24.30
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found SDL2: /usr/lib64/libSDL2main.a;/usr/lib64/libSDL2.so;-lpthread  
CMake Error at src/CMakeLists.txt:224 (message):
  OpenGL is required for building.


-- Configuring incomplete, errors occurred!
See also "/home/coni/.cache/pacaur/gzdoom/src/gzdoom/CMakeFiles/CMakeOutput.log".
See also "/home/coni/.cache/pacaur/gzdoom/src/gzdoom/CMakeFiles/CMakeError.log".
==> ERROR: A failure occurred in prepare().
    Aborting...
:: fmodex4.26.36 is a new orphan package
:: failed to build gzdoom package(s)

**Comment by corngood** [comment]
I think I'm going to get rid of the ld.conf and symlink all the libs into /usr/lib.  Anyone object?

**Comment by conihorse** [comment]
I'm too ignorant to have an opinion :+1:

**Comment by headkase** [comment]
Same here, I don't know enough to have a valid opinion.

**Comment by kikijiki** [comment]
I have the same problem.
libGL.so is present but there is no GL/gl.h.

**Comment by corngood** [comment]
You should install 'mesa', but not 'mesa-libgl'.

**Comment by kikijiki** [comment]
@corngood That makes sense, thank you.
